<?xml version="1.0" encoding="UTF-8"?><testrun name="TestMaximos" project="PracticaMaximosYMinimos" tests="2" started="2" failures="1" errors="0" ignored="0">
  <testsuite name="test.TestMaximos" time="0.007" displayname="TestMaximos" uniqueid="[engine:junit-jupiter]/[class:test.TestMaximos]">
    <testcase name="testMaximoDe2EnterosPositivos" classname="test.TestMaximos" time="0.003" displayname="testMaximoDe2EnterosPositivos()" uniqueid="[engine:junit-jupiter]/[class:test.TestMaximos]/[method:testMaximoDe2EnterosPositivos()]">
      <failure>
        <expected>3</expected>
        <actual>5</actual>
        org.opentest4j.AssertionFailedError: expected: &lt;3&gt; but was: &lt;5&gt;&#13;
	at org.junit.jupiter.api.AssertionFailureBuilder.build(AssertionFailureBuilder.java:151)&#13;
	at org.junit.jupiter.api.AssertionFailureBuilder.buildAndThrow(AssertionFailureBuilder.java:132)&#13;
	at org.junit.jupiter.api.AssertEquals.failNotEqual(AssertEquals.java:197)&#13;
	at org.junit.jupiter.api.AssertEquals.assertEquals(AssertEquals.java:150)&#13;
	at org.junit.jupiter.api.AssertEquals.assertEquals(AssertEquals.java:145)&#13;
	at org.junit.jupiter.api.Assertions.assertEquals(Assertions.java:527)&#13;
	at test.TestMaximos.testMaximoDe2EnterosPositivos(TestMaximos.java:13)&#13;
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)&#13;
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)&#13;
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)&#13;
&#13;

      </failure>
    </testcase>
    <testcase name="testMaximoDe3EnterosPositivos" classname="test.TestMaximos" time="0.003" displayname="testMaximoDe3EnterosPositivos()" uniqueid="[engine:junit-jupiter]/[class:test.TestMaximos]/[method:testMaximoDe3EnterosPositivos()]"/>
  </testsuite>
</testrun>
